/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Fri May 17 16:31:53 2019";
extern const char kBuilderName[] = "TianMeng";
extern const char kHostName[] = "dev2.trio.ai";
extern const char kCompiler[] = "GCC 4.8.5";
}}
