/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit 37f3cf0cb5967eeea2b5cda3ad433ed61fe17b27\n"
"Author: TianMeng <tianmeng@localhost>\n"
"Date:   Fri May 17 16:41:04 2019 +0800\n"
"\n"
"    first commit\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Fri May 17 17:48:47 2019";
extern const char kBuilderName[] = "TianMeng";
extern const char kHostName[] = "dev2.trio.ai";
extern const char kCompiler[] = "GCC 4.8.5";
}}
